[workspace]
members = ["lightning", "api"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Johannes Neyer"]
license = "MIT"

[workspace.dependencies]
log = "0.4.20"
